---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookslib
  labels:
    app: bookslib
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookslib
  template:
    metadata:
      labels:
        app: bookslib
    spec:
      containers:
        - name: bookslib
          image: azuccarella/bookslib
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: bookslib-env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bookslib-env
  namespace: default
data:
  DB_HOST: bookslib-db
  DB_PORT: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: bookslib-service
spec:
  type: NodePort
  selector:
    app: bookslib
  ports:
    - name: http
      port: 8001
      targetPort: 8001