---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
  labels:
    app: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - name: customer
          image: azuccarella/customers
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: customers-env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customers-env
  namespace: default
data:
  DB_HOST: customers-db
  DB_PORT: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  type: NodePort
  selector:
    app: customers
  ports:
    - name: http
      port: 8000
      targetPort: 8000