---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: azuccarella/orders
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: orders-env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-env
  namespace: default
data:
  DB_HOST: orders-db
  DB_PORT: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  type: NodePort
  selector:
    app: orders
  ports:
    - name: http
      port: 8002
      targetPort: 8002